### ISSUE TITLE
Relaxing `torch>=1.8.0` dependency to avoid long installation in collab ?

### ISSUE THREAD

**Issue by mitkotak** [Linux-cpp-lisp/opt_einsum_fx#17]
Have been trying to get rid of the long installation time in google collab by relaxing the [`torch>=1.8.0` dependency](https://github.com/mitkotak/e3nn/commit/170513163226e4586f8646107dbf7c52c9f5b377) but seems like its creeping in from here. Are you open to relaxing the dependency or having an alternate version that I can depend on ?

**Comment by mariogeiger** [comment]
@Linux-cpp-lisp

**Comment by Linux-cpp-lisp** [comment]
Not sure I follow, why does having a `torch` minimum make installation time a problem in Colab?  What would relaxing the requirement look like?  `torch.fx` was introduced in 1.8, having something older than 1.8 will not work.
